from dotenv import dotenv_values

config = dotenv_values(".env")

HOST = config["HOST"]
PORT = config["PORT"]

DB_COLLECTION_NAME_PROJECTS = config["DB_COLLECTION_NAME_PROJECTS"]
DB_COLLECTION_NAME_STATEMENTS = config["DB_COLLECTION_NAME_STATEMENTS"]
DB_COLLECTION_NAME_USERS = config["DB_COLLECTION_NAME_USERS"]
DB_COLLECTION_NAME_CONNECTIONS = config["DB_COLLECTION_NAME_CONNECTIONS"]
DB_CONNECTION_STRING = config["DB_CONNECTION_STRING"]

DB_NAME = config["DB_NAME"]
