name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  
  workflow_dispatch:
    branches: ["master"]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.0.0
    - name: Build the Docker image
      run: docker build . --file productoin.Dockerfile --tag raphel2b3/swarmintelligencebackend:$(date +%s)
