name: Docker Image CI

on:
  #push:
   # branches: [ "master" ]
  #pull_request:
  #  branches: [ "master" ]
  workflow_dispatch:
        
    
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: ls
    - name: Build the Docker image
      run: docker build --file production.Dockerfile --tag raphel2b3/swarmintelligencebackend:$(date +%s) .
